{
 "title": "AQUIFER - CRCC",
 "description": "Piezometer Metwork",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NP -  [m snm]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "rawSql": "  SELECT\n    $__timeGroupAlias(timestamp,$__interval),\n    a.id AS metric,\n     avg(b.zb-b.pi+data) AS \"data\"\n  FROM datos_campo a, sites b\n  WHERE\n    $__timeFilter(timestamp) AND\n     a.id=b.id and topic = '0001'\n  GROUP BY 1,2\n  ORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Conductivity  [uS/cm]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  id AS metric,\n  avg(data) AS \"data\"\nFROM datos_campo\nWHERE\n  $__timeFilter(timestamp) AND\n  topic = '0004'\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Temperature [ºC]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  id AS metric,\n  avg(data) AS \"data\"\nFROM datos_campo\nWHERE\n  $__timeFilter(timestamp) AND\n  topic = '0002'\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "PROBES",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  id AS ID,  name AS NAME, maps_url\r\nFROM sites "
    }
   ]
  },
  {
   "title": "GIS - Water level to surface  [m] (last value)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT z-(zb-pi+data) data,name,geohash\r\n from datos_campo a,sites b\r\n where topic='0001' and a.id=b.id AND\r\n timestamp = (select max(timestamp) from datos_campo where topic='0001')\r\n"
    }
   ]
  },
  { "title": "Device Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "GSM signal  [db]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  id AS metric,\n  avg(data) AS \"data\"\nFROM datos_campo\nWHERE\n  $__timeFilter(timestamp) AND\n  topic = '0008'\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Battery Level  [v]",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  id AS metric,\n  avg(data) AS \"data\"\nFROM datos_campo\nWHERE\n  $__timeFilter(timestamp) AND\n  topic = '0003'\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  { "title": "Schemes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Installation",
   "type": "text",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 43 },
   "options": {
    "content": "<img src=\"https://www.crcc.es/wp-content/uploads/2022/03/Esquema.png\">        \n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Installation",
   "type": "text",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 43 },
   "options": {
    "content": "<img src=\"https://www.crcc.es/wp-content/uploads/2022/03/Leyenda.png\">        \n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  }
 ]
}